const fs=require('fs');
const vm=require('vm');
const content=fs.readFileSync('dist/content.js','utf8');
const app=fs.readFileSync('dist/app.js','utf8');
const elements=new Map();
const document={querySelectorAll:()=>[],querySelector:selector=>{if(!elements.has(selector))elements.set(selector,{setAttribute(){}});return elements.get(selector)},title:''};
const context={window:{},document,URL,Date};
vm.createContext(context);
vm.runInContext(content,context);
vm.runInContext(app.slice(0,app.indexOf('const menu=')),context);
let html=fs.readFileSync('dist/index.html','utf8');
html=html.replace(/<section class="hero" id="home">[\s\S]*?<\/section>/,'<section class="hero" id="home">'+elements.get('.hero').innerHTML+'</section>');
const a=html.indexOf('<div id="sections">'),b=html.indexOf('\n</main>',a);
if(a<0||b<0)throw new Error('Page section markers missing');
html=html.slice(0,a)+'<div id="sections">'+elements.get('#sections').innerHTML+'</div>'+html.slice(b);
html=html.replace(/<a class="wordmark"[^>]*>[\s\S]*?<\/a>/,'<a class="wordmark" href="#home" aria-label="Nasrin Kunhimoidu — home">Nasrin<span>.</span></a>');
if(!html.includes('<noscript>'))html=html.replace('</head>','<noscript><style>.reveal{opacity:1!important;transform:none!important}</style></noscript>\n</head>');
fs.writeFileSync('dist/index.html',html);
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);
if(new Set(ids).size!==ids.length)throw new Error('Duplicate HTML ids');
const refs=[...html.matchAll(/(?:src|href)="([^"#]+)"/g)].map(x=>x[1]).filter(x=>!/^https?:|^mailto:|^tel:|^data:/.test(x));
for(const p of refs)if(!fs.existsSync('dist/'+p))throw new Error('Missing asset '+p);
for(const match of html.matchAll(/href="#([^"]+)"/g))if(!ids.includes(match[1]))throw new Error('Missing section '+match[1]);
console.log('Static HTML rendered; all local assets and section links verified.');
